export const rubyChallenges = [
  {
    id: 'ruby-map-squares',
    category: 'ruby-enumerables',
    domain: 'ruby',
    subcategory: 'enumerables',
    type: 'ruby',
    title: 'Ruby: Array Transformation (map)',
    resource: 'resources/ruby/basics/enumerables.rb',
    task: 'Given [1, 2, 3, 4, 5], square each number using .map.',
    hint: '[1, 2, 3, 4, 5].map { |n| n ** 2 }',
    expectedOutput: '[1, 4, 9, 16, 25]',
    solution: '[1, 2, 3, 4, 5].map { |n| n ** 2 }'
  },
  {
    id: 'ruby-select-evens',
    category: 'ruby-enumerables',
    domain: 'ruby',
    subcategory: 'enumerables',
    type: 'ruby',
    title: 'Ruby: Filter Elements (select / &:even?)',
    resource: 'resources/ruby/basics/enumerables.rb',
    task: 'Filter only even numbers from [1, 2, 3, 4, 5, 6] using .select.',
    hint: '[1, 2, 3, 4, 5, 6].select(&:even?)',
    expectedOutput: '[2, 4, 6]',
    solution: '[1, 2, 3, 4, 5, 6].select(&:even?)'
  },
  {
    id: 'ruby-tally-frequencies',
    category: 'ruby-enumerables',
    domain: 'ruby',
    subcategory: 'enumerables',
    type: 'ruby',
    title: 'Ruby: Count Occurrences (tally)',
    resource: 'resources/ruby/basics/enumerables.rb',
    task: 'Count the frequency of each fruit in %w[apple banana apple orange banana apple] using .tally.',
    hint: '%w[apple banana apple orange banana apple].tally',
    expectedOutput: '{"apple"=>3, "banana"=>2, "orange"=>1}',
    solution: '%w[apple banana apple orange banana apple].tally'
  },
  {
    id: 'ruby-reduce-product',
    category: 'ruby-enumerables',
    domain: 'ruby',
    subcategory: 'enumerables',
    type: 'ruby',
    title: 'Ruby: Accumulation (reduce / inject)',
    resource: 'resources/ruby/basics/enumerables.rb',
    task: 'Compute the factorial/product of [1, 2, 3, 4, 5] using .reduce(:*).',
    hint: '[1, 2, 3, 4, 5].reduce(:*)',
    expectedOutput: '120',
    solution: '[1, 2, 3, 4, 5].reduce(:*)'
  },
  {
    id: 'ruby-group-by-length',
    category: 'ruby-enumerables',
    domain: 'ruby',
    subcategory: 'enumerables',
    type: 'ruby',
    title: 'Ruby: Group By Property (group_by)',
    resource: 'resources/ruby/basics/enumerables.rb',
    task: 'Group words in %w[cat dog elephant bird duck] by their length using .group_by(&:length).',
    hint: '%w[cat dog elephant bird duck].group_by(&:length)',
    expectedOutput: '{3=>["cat", "dog"], 8=>["elephant"], 4=>["bird", "duck"]}',
    solution: '%w[cat dog elephant bird duck].group_by(&:length)'
  },
  {
    id: 'ruby-flat-map',
    category: 'ruby-enumerables',
    domain: 'ruby',
    subcategory: 'enumerables',
    type: 'ruby',
    title: 'Ruby: Flattened Mapping (flat_map)',
    resource: 'resources/ruby/basics/enumerables.rb',
    task: 'Multiply each element in nested array [[1, 2], [3, 4]] by 10 and return a single flattened array using .flat_map.',
    hint: '[[1, 2], [3, 4]].flat_map { |arr| arr.map { |x| x * 10 } }',
    expectedOutput: '[10, 20, 30, 40]',
    solution: '[[1, 2], [3, 4]].flat_map { |arr| arr.map { |x| x * 10 } }'
  },
  {
    id: 'ruby-each-with-object',
    category: 'ruby-enumerables',
    domain: 'ruby',
    subcategory: 'enumerables',
    type: 'ruby',
    title: 'Ruby: State Accumulation (each_with_object)',
    resource: 'resources/ruby/basics/enumerables.rb',
    task: 'Map array %w[a b c] to a hash where each key maps to its uppercase letter using .each_with_object({}).',
    hint: '%w[a b c].each_with_object({}) { |char, h| h[char] = char.upcase }',
    expectedOutput: '{"a"=>"A", "b"=>"B", "c"=>"C"}',
    solution: '%w[a b c].each_with_object({}) { |char, h| h[char] = char.upcase }'
  },
  {
    id: 'ruby-symbol-to-proc',
    category: 'ruby-blocks',
    domain: 'ruby',
    subcategory: 'blocks',
    type: 'ruby',
    title: 'Ruby: Symbol-to-Proc Shorthand (&:method)',
    resource: 'resources/ruby/basics/blocks_procs_lambdas.rb',
    task: 'Convert array of strings %w[ruby rails gems] to uppercase using &:upcase.',
    hint: '%w[ruby rails gems].map(&:upcase)',
    expectedOutput: '["RUBY", "RAILS", "GEMS"]',
    solution: '%w[ruby rails gems].map(&:upcase)'
  },
  {
    id: 'ruby-custom-yield',
    category: 'ruby-blocks',
    domain: 'ruby',
    subcategory: 'blocks',
    type: 'ruby',
    title: 'Ruby: Method Yield (yield)',
    resource: 'resources/ruby/basics/blocks_procs_lambdas.rb',
    task: 'Define method `with_greeting(name)` that yields "Hello, #{name}!", call it with "Ruby", and uppercase the yielded message in a block.',
    hint: 'def with_greeting(name); yield("Hello, #{name}!"); end; with_greeting("Ruby") { |msg| msg.upcase }',
    expectedOutput: 'HELLO, RUBY!',
    solution: 'def with_greeting(name); yield("Hello, #{name}!"); end; with_greeting("Ruby") { |msg| msg.upcase }'
  },
  {
    id: 'ruby-lambda-call',
    category: 'ruby-blocks',
    domain: 'ruby',
    subcategory: 'blocks',
    type: 'ruby',
    title: 'Ruby: Lambda Closure (->(args) { ... })',
    resource: 'resources/ruby/basics/blocks_procs_lambdas.rb',
    task: 'Define a lambda multiplying two numbers `->(x, y) { x * y }` and call it with arguments 6 and 7.',
    hint: 'mult = ->(x, y) { x * y }; mult.call(6, 7)',
    expectedOutput: '42',
    solution: 'mult = ->(x, y) { x * y }; mult.call(6, 7)'
  },
  {
    id: 'ruby-hash-default',
    category: 'ruby-hashes',
    domain: 'ruby',
    subcategory: 'hashes',
    type: 'ruby',
    title: 'Ruby: Hash Default Values (Hash.new(0))',
    resource: 'resources/ruby/basics/hashes_symbols.rb',
    task: 'Initialize a frequency counter with `Hash.new(0)`, increment for each char in %w[a b a c a b], and return the hash.',
    hint: 'freq = Hash.new(0); %w[a b a c a b].each { |c| freq[c] += 1 }; freq',
    expectedOutput: '{"a"=>3, "b"=>2, "c"=>1}',
    solution: 'freq = Hash.new(0); %w[a b a c a b].each { |c| freq[c] += 1 }; freq'
  },
  {
    id: 'ruby-hash-dig',
    category: 'ruby-hashes',
    domain: 'ruby',
    subcategory: 'hashes',
    type: 'ruby',
    title: 'Ruby: Safe Nested Hash Navigation (dig)',
    resource: 'resources/ruby/basics/hashes_symbols.rb',
    task: 'Extract the nested city from { user: { address: { city: "Austin" } } } using .dig.',
    hint: '{ user: { address: { city: "Austin" } } }.dig(:user, :address, :city)',
    expectedOutput: 'Austin',
    solution: '{ user: { address: { city: "Austin" } } }.dig(:user, :address, :city)'
  },
  {
    id: 'ruby-hash-slice',
    category: 'ruby-hashes',
    domain: 'ruby',
    subcategory: 'hashes',
    type: 'ruby',
    title: 'Ruby: Extract Hash Subsets (slice)',
    resource: 'resources/ruby/basics/hashes_symbols.rb',
    task: 'Extract only :host and :port from { host: "localhost", port: 5432, db: "prod", user: "app" } using .slice.',
    hint: '{ host: "localhost", port: 5432, db: "prod", user: "app" }.slice(:host, :port)',
    expectedOutput: '{host: "localhost", port: 5432}',
    solution: '{ host: "localhost", port: 5432, db: "prod", user: "app" }.slice(:host, :port)'
  },
  {
    id: 'ruby-hash-transform-keys',
    category: 'ruby-hashes',
    domain: 'ruby',
    subcategory: 'hashes',
    type: 'ruby',
    title: 'Ruby: Transform Keys (transform_keys)',
    resource: 'resources/ruby/basics/hashes_symbols.rb',
    task: 'Convert string keys {"name" => "alice", "role" => "admin"} to symbols using transform_keys(&:to_sym).',
    hint: '{"name" => "alice", "role" => "admin"}.transform_keys(&:to_sym)',
    expectedOutput: '{name: "alice", role: "admin"}',
    solution: '{"name" => "alice", "role" => "admin"}.transform_keys(&:to_sym)'
  },
  {
    id: 'ruby-hash-transform-values',
    category: 'ruby-hashes',
    domain: 'ruby',
    subcategory: 'hashes',
    type: 'ruby',
    title: 'Ruby: Transform Values (transform_values)',
    resource: 'resources/ruby/basics/hashes_symbols.rb',
    task: 'Double all values in hash { a: 10, b: 20, c: 30 } using .transform_values.',
    hint: '{ a: 10, b: 20, c: 30 }.transform_values { |v| v * 2 }',
    expectedOutput: '{a: 20, b: 40, c: 60}',
    solution: '{ a: 10, b: 20, c: 30 }.transform_values { |v| v * 2 }'
  },
  {
    id: 'ruby-string-gsub-regex',
    category: 'ruby-strings',
    domain: 'ruby',
    subcategory: 'strings',
    type: 'ruby',
    title: 'Ruby: Regex Substitution (gsub)',
    resource: 'resources/ruby/basics/strings_regex.rb',
    task: 'Replace all numbers in "Order 1234 on item 567" with "XXX" using .gsub and regex /\\d+/.',
    hint: '"Order 1234 on item 567".gsub(/\\d+/, "XXX")',
    expectedOutput: 'Order XXX on item XXX',
    solution: '"Order 1234 on item 567".gsub(/\\d+/, "XXX")'
  },
  {
    id: 'ruby-class-attr-accessor',
    category: 'ruby-oop',
    domain: 'ruby',
    subcategory: 'oop',
    type: 'ruby',
    title: 'Ruby: Class Attributes (attr_accessor)',
    resource: 'resources/ruby/oop/classes_inheritance.rb',
    task: 'Define class User with attr_accessor :name and initialize(n), create User.new("Alice"), change name to "Bob", and return .name.',
    hint: 'class User; attr_accessor :name; def initialize(n); @name = n; end; end; u = User.new("Alice"); u.name = "Bob"; u.name',
    expectedOutput: 'Bob',
    solution: 'class User; attr_accessor :name; def initialize(n); @name = n; end; end; u = User.new("Alice"); u.name = "Bob"; u.name'
  },
  {
    id: 'ruby-class-method-self',
    category: 'ruby-oop',
    domain: 'ruby',
    subcategory: 'oop',
    type: 'ruby',
    title: 'Ruby: Class Methods (def self.method)',
    resource: 'resources/ruby/oop/classes_inheritance.rb',
    task: 'Define class MathUtil with class method `def self.square(n); n * n; end` and call MathUtil.square(9).',
    hint: 'class MathUtil; def self.square(n); n * n; end; end; MathUtil.square(9)',
    expectedOutput: '81',
    solution: 'class MathUtil; def self.square(n); n * n; end; end; MathUtil.square(9)'
  },
  {
    id: 'ruby-super-inheritance',
    category: 'ruby-oop',
    domain: 'ruby',
    subcategory: 'oop',
    type: 'ruby',
    title: 'Ruby: Method Inheritance (super)',
    resource: 'resources/ruby/oop/classes_inheritance.rb',
    task: 'Define class Base with `def run; "Base"; end`, subclass Sub < Base with `def run; "#{super} -> Sub"; end`, and call Sub.new.run.',
    hint: 'class Base; def run; "Base"; end; end; class Sub < Base; def run; "#{super} -> Sub"; end; end; Sub.new.run',
    expectedOutput: 'Base -> Sub',
    solution: 'class Base; def run; "Base"; end; end; class Sub < Base; def run; "#{super} -> Sub"; end; end; Sub.new.run'
  },
  {
    id: 'ruby-module-mixin',
    category: 'ruby-oop',
    domain: 'ruby',
    subcategory: 'oop',
    type: 'ruby',
    title: 'Ruby: Module Mixin (include)',
    resource: 'resources/ruby/modules/basics.rb',
    task: 'Define module Greetable with method `def greet; "Hello from module!"; end`, include it in class Robot, instantiate Robot.new and call .greet.',
    hint: 'module Greetable; def greet; "Hello from module!"; end; end; class Robot; include Greetable; end; Robot.new.greet',
    expectedOutput: 'Hello from module!',
    solution: 'module Greetable; def greet; "Hello from module!"; end; end; class Robot; include Greetable; end; Robot.new.greet'
  }
];
